from blogfront import BlogFront
from bloghandler import BlogHandler
from deletecomment import DeleteComment
from deletepost import DeletePost
from editcomment import EditComment
from editpost import EditPost
from login import Login
from logout import Logout
from newpost import NewPost
from postpage import PostPage
from register import Register
